# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3246f81db8d03eca873fb0a3e063ff0f81da6696037f1ccc33976af5b9f256f46b8ef7fb0740ee978938fed63a578895eecb276a1bb658d0a530cffe8d9e8bf3

test:
  secret_key_base: 9ae7b366611c286866a363aa751850ffb32be9d9601263a9bc55b7d32620a36bacb9fa48d45ff580053b33bccce429965f0f9482eb0879a0b97d48cd74d26dcd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
